def v2():
    music.play_tone(494, music.beat(BeatFraction.HALF))
    music.play_tone(494, music.beat(BeatFraction.QUARTER))
    music.play_tone(494, music.beat(BeatFraction.HALF))
    music.play_tone(494, music.beat(BeatFraction.QUARTER))
    music.play_tone(415, music.beat(BeatFraction.HALF))
    music.play_tone(370, music.beat(BeatFraction.WHOLE))
    music.play_tone(370, music.beat(BeatFraction.QUARTER))
    music.play_tone(415, music.beat(BeatFraction.QUARTER))
    music.play_tone(494, music.beat(BeatFraction.HALF))

def on_button_pressed_a():
    music.set_volume(100)
    music.set_tempo(100)
    v1()
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    v2()
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    v1()
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.play_tone(659, music.beat(BeatFraction.QUARTER))
    music.play_tone(740, music.beat(BeatFraction.HALF))
    music.play_tone(622, music.beat(BeatFraction.HALF))
    music.play_tone(554, music.beat(BeatFraction.DOUBLE))
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    v1()
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    v2()
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    v1()
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.play_tone(659, music.beat(BeatFraction.QUARTER))
    music.play_tone(740, music.beat(BeatFraction.HALF))
    music.play_tone(622, music.beat(BeatFraction.HALF))
    music.play_tone(554, music.beat(BeatFraction.WHOLE))
    music.play_tone(494, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.play_tone(622, music.beat(BeatFraction.WHOLE))
    music.play_tone(554, music.beat(BeatFraction.WHOLE))
    music.play_tone(466, music.beat(BeatFraction.HALF))
    music.play_tone(494, music.beat(BeatFraction.BREVE))
    music.rest(music.beat(BeatFraction.SIXTEENTH))
input.on_button_pressed(Button.A, on_button_pressed_a)

def v1():
    music.play_tone(494, music.beat(BeatFraction.HALF))
    music.play_tone(494, music.beat(BeatFraction.QUARTER))
    music.play_tone(494, music.beat(BeatFraction.HALF))
    music.play_tone(740, music.beat(BeatFraction.HALF))
    music.play_tone(554, music.beat(BeatFraction.WHOLE))
    music.play_tone(622, music.beat(BeatFraction.WHOLE))