input.onButtonPressed(Button.A, function () {
    music.ringTone(349)
    music.rest(music.beat(BeatFraction.Sixteenth))
})
function v1 () {
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(740, music.beat(BeatFraction.Half))
    music.playTone(554, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
}
music.setVolume(100)
music.setTempo(100)
v1()
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(494, music.beat(BeatFraction.Half))
music.playTone(494, music.beat(BeatFraction.Half))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Half))
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(494, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
v1()
